### PR TITLE
Fixes #36 - Add Drupal 9 compatibility

### LINKED ISSUE #36: Drupal 9 compatibility
Code report:

CONTRIBUTED PROJECTS
--------------------------------------------------------------------------------
GraphQL Views 8.x-1.0
Scanned on Wed, 06/03/2020 - 23:52.

1 error found. 8 warnings found.

modules/contrib/graphql_views/src/Plugin/views/row/GraphQLEntityRow.php:
┌─────────┬──────┬──────────────────────────────────────────────────────────────┐
│ STATUS  │ LINE │                           MESSAGE                            │
├─────────┼──────┼──────────────────────────────────────────────────────────────┤
│ Fix now │ 64   │ Parameter $entityManager of method                           │
│         │      │ Drupal\graphql_views\Plugin\views\row\GraphQLEntityRow::__co │
│         │      │ nstruct() has typehint with deprecated interface             │
│         │      │ Drupal\Core\Entity\EntityManagerInterface. Deprecated in     │
│         │      │ drupal:8.0.0 and is removed from drupal:9.0.0.               │
│         │      │                                                              │
└─────────┴──────┴──────────────────────────────────────────────────────────────┘

modules/contrib/graphql_views/tests/src/Kernel/ContextualViewsTest.php:
┌──────────┬──────┬───────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                          MESSAGE                          │
├──────────┼──────┼───────────────────────────────────────────────────────────┤
│ Check    │      │ Class Drupal\Tests\graphql_views\Kernel\ViewsTestBase not │
│ manually │      │ found and could not be autoloaded.                        │
│          │      │                                                           │
│ Check    │ 12   │ Class Drupal\Tests\graphql_views\Kernel\ViewsTestBase not │
│ manually │      │ found and could not be autoloaded.                        │
│          │      │                                                           │
└──────────┴──────┴───────────────────────────────────────────────────────────┘

modules/contrib/graphql_views/tests/src/Kernel/ViewsTest.php:
┌──────────┬──────┬───────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                          MESSAGE                          │
├──────────┼──────┼───────────────────────────────────────────────────────────┤
│ Check    │      │ Class Drupal\Tests\graphql_views\Kernel\ViewsTestBase not │
│ manually │      │ found and could not be autoloaded.                        │
│          │      │                                                           │
│ Check    │ 11   │ Class Drupal\Tests\graphql_views\Kernel\ViewsTestBase not │
│ manually │      │ found and could not be autoloaded.                        │
│          │      │                                                           │
└──────────┴──────┴───────────────────────────────────────────────────────────┘

modules/contrib/graphql_views/tests/src/Kernel/ViewsTestBase.php:
┌──────────┬──────┬─────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                           │
├──────────┼──────┼─────────────────────────────────────────────────────────────┤
│ Check    │      │ Class                                                       │
│ manually │      │ Drupal\Tests\graphql_core\Kernel\GraphQLContentTestBase not │
│          │      │ found and could not be autoloaded.                          │
│          │      │                                                             │
│ Check    │ 17   │ Class                                                       │
│ manually │      │ Drupal\Tests\graphql_core\Kernel\GraphQLContentTestBase not │
│          │      │ found and could not be autoloaded.                          │
│          │      │                                                             │
└──────────┴──────┴─────────────────────────────────────────────────────────────┘

modules/contrib/graphql_views/graphql_views.info.yml:
┌──────────┬──────┬────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                          MESSAGE                           │
├──────────┼──────┼────────────────────────────────────────────────────────────┤
│ Check    │ 0    │ Add <code>core_version_requirement: ^8 || ^9</code> to     │
│ manually │      │ modules/contrib/graphql_views/graphql_views.info.yml to    │
│          │      │ designate that the module is compatible with Drupal 9. See │
│          │      │ https://drupal.org/node/3070687.                           │
│          │      │                                                            │
└──────────┴──────┴────────────────────────────────────────────────────────────┘

modules/contrib/graphql_views/tests/modules/graphql_views_test/graphql_views_tes
t.info.yml:
┌──────────┬──────┬──────────────────────────────────────────────────────────────┐
│  STATUS  │ LINE │                           MESSAGE                            │
├──────────┼──────┼──────────────────────────────────────────────────────────────┤
│ Check    │ 0    │ Add <code>core_version_requirement: ^8 || ^9</code> to       │
│ manually │      │ modules/contrib/graphql_views/tests/modules/graphql_views_te │
│          │      │ st/graphql_views_test.info.yml to designate that the module  │
│          │      │ is compatible with Drupal 9. See                             │
│          │      │ https://drupal.org/node/3070687.                             │
│          │      │                                                              │
└──────────┴──────┴──────────────────────────────────────────────────────────────┘

### PR DESCRIPTION
**Pull request by dan2k3k4**

### CODE REVIEW

**Review by ayalon — APPROVED** [review]
Looks fine to me! Thanks for your work.

**Review by ayalon — APPROVED** [review]

**Comment by dan2k3k4** [comment]
Perhaps @pmelab or @klausi could check this PR and do a D9 release?

**Comment by klausi** [comment]
Sorry, I'm not maintaining this module, maybe @pmelab knows or someone else could take over :)

**Comment by ayalon** [comment]
This module is also blocking a Drupal 9 upgrade on our side. If I can help, just contact me.

**Pull request merged**
